name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push Frontend Image 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chiso1/frontend:latest
          context: ./frontend
      -
        name: Build and push Backend Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chiso1/backend:latest
          context: ./api
