name: CI2

on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

jobs:
   build:

     runs-on: ubuntu-latest

     strategy:
       matrix:
         node-version: [14.x]

     steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: Install dependencies 📦
       #Using npm ci is generally faster than running npm install
       run: |
         cd frontend
         npm ci
     - name: Build the app 🏗
       run: |
         cd frontend
         npm run build
     - name: Run component tests 🔸
       run: |
         cd frontend
         npm run test
     - name: Start the app 📤
       run: |
         cd frontend
         npm start &
         npx wait-on --timeout 60000
 
